export const UPDATE_TOTAL = "UPDATE_TOTAL";
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CLEAR_QUANTITIES = "CLEAR_QUANTITIES";
